import React from "react";
import type { Metadata } from "next";
import {
  Inter as FontBody,
  Playfair_Display as FontDisplay,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import BackgroundCircles from "@/components/background-circles";
import SocialMediaLinks from "@/components/social-media-links";
import StuchlyfLogoFull from "@/components/svg/stuchlyf-logo-full";

const fontDisplay = FontDisplay({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  variable: "--font-display",
});

const fontBody = FontBody({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "stuchlyf.",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // @ts-ignore
  return (
    <html lang="en" className={"snap-y snap-proximity scroll-smooth"}>
      <body
        className={cn(
          "dark min-h-screen bg-background font-body antialiased",
          fontBody.variable,
          fontDisplay.variable,
        )}
      >
        {children}
        <footer className={"container pb-4 pt-16"}>
          <div className={"mb-2 flex justify-center gap-8 text-sm"}>
            <StuchlyfLogoFull className={"w-48 opacity-70"} />
          </div>
          <div
            className={
              "flex flex-wrap justify-center gap-x-4 gap-y-1 text-xs font-light opacity-70"
            }
          >
            <span>Copyright &copy;2024 Florian Stuchly</span>
          </div>
        </footer>
        {/*@ts-ignore*/}
        <BackgroundCircles />
        {/*@ts-ignore*/}
        <SocialMediaLinks />
      </body>
    </html>
  );
}
